### PR TITLE
upgrade virtual-env

### PR DESCRIPTION
**Pull request by davidkarlsen**

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@paolomainardi a lot of back and forth with this `toolset.json` file - want to take a look? https://github.com/evryfs/github-actions-runner/runs/1744996841?check_suite_focus=true#step:6:1091

**Comment by paolomainardi** [comment]
hi @davidkarlsen yes i can help, what is the problem ?

**Comment by davidkarlsen** [comment]
> hi @davidkarlsen yes i can help, what is the problem ?

thanks, see: https://github.com/evryfs/github-actions-runner/runs/1817781345?check_suite_focus=true#step:6:1048

**Comment by davidkarlsen** [comment]
Obsoleted

**Pull request closed without merging**
